apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-client
  labels:
    app: eos-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-client
  template:
    metadata:
      labels:
        app: eos-client
    spec:
      containers:
        - name: eos-client
          image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest
          command: ["sleep", "100000"]
          volumeMounts:
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
      volumes:
        - name: eos
          # Note the particularity of the host path being /var/eos, not /eos.
          # The path inside the container will be /eos with this sample setup.
          hostPath:
            path: /var/eos
      securityContext:
        seLinuxOptions:
          type: "spc_t"