name: Singularity Build (manual)
on: 
  push:
    branches:
      -  containers

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}-base-container
  IMAGE_NAME: base-container

jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    # container:
      # image: quay.io/singularity/singularity:v3.8.3
    strategy:
      fail-fast: false
      matrix:
        recipe: ["ai/containers/base-container.def"]

    name: Check ${{ matrix.recipe }}
    steps:

      - name: Check out code for the container build
        uses: actions/checkout@v3

      - name: list directories
        run: |
          ls
          ls ai
          ls ai/env-files/

      - name: Continue if requirements file xists
        run: |
          if test -f ai/env-files/pytorch-env-container.txt; then
              echo "keepgoing=true" >> $GITHUB_ENV
          fi
 
      - name: Continue if Singularity Recipe Exists
        run: |
          if [[ -f "${{ matrix.recipe }}" ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi      

      - name: Set up Go 1.19
        if: ${{ env.keepgoing == 'true' }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go

      - name: Install Dependencies
        if: ${{ env.keepgoing == 'true' }}
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        if: ${{ env.keepgoing == 'true' }}
        env:
          SINGULARITY_VERSION: 3.11.3
          GOPATH: /tmp/go
      
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install 


      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.recipe }}
        run: |
         ls 
         if [ -f "${{ matrix.recipe }}" ]; then
            CONTAINER_NAME=${{ matrix.recipe }}
            CONTAINER_NAME="${CONTAINER_NAME%.*}"
            echo "container name is $CONTAINER_NAME."
            echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
            sudo -E singularity build $CONTAINER_NAME.sif ${{ matrix.recipe }}
            tag=$(echo "${recipe/Singularity\./}")
            if [ "$tag" == "Singularity" ]; then
                tag=latest
            else
                tag=dev
            fi
            # Build the container and name by tag
            echo "Tag is $tag."
            echo "tag=$tag" >> $GITHUB_ENV
         else
           echo "${{ matrix.recipe }} is not found."
           echo "Present working directory: $PWD"
           ls
         fi

      - name: Push image to github registry
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
            if [[ "${keepgoing}" == "true" ]]; then
                # echo "GITHUB_REPOSITORY is ${GITHUB_REPOSITORY}"
                # echo "IMAGE_NAME will be {CONTAINER_NAME}:"
                # echo "IMAGE_NAME=$CONTAINER_NAME"
                echo "REGISTRY is $REGISTRY"
                echo "IMAGE_NAME is $IMAGE_NAME"
                echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
                # Both ways of pushing images works indeed
                singularity push $CONTAINER_NAME.sif oras://ghcr.io/${GITHUB_REPOSITORY}-${IMAGE_NAME}:${tag}
                #singularity push $CONTAINER_NAME.sif oras://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${tag}
            fi