name: Build Docs with Sphinx

on:
  push:
  pull_request:

jobs:
  build-docs:
    name: Build docs with Sphinx
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive  # Ensure submodules are cloned

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev pandoc python3-sphinx

      # Step 3: Set up Python and virtual environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: Set up virtual environment
        run: |
          python -m venv .venv-docs
          source .venv-docs/bin/activate
          pip install --upgrade pip
          pip install ".[torch,docs,linux]"

      # Step 4: Build the Sphinx documentation
      - name: Build docs
        run: |
          source .venv-docs/bin/activate
          cd docs
          make clean
          make html
